<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Asusf15" failures="1" tests="1" name="com.LUMA.testRunner.LumaCheckoutProcessTestRunner" time="86.893" errors="0" timestamp="2025-03-23T18:11:12 IST" skipped="0">
  <testcase classname="com.LUMA.testRunner.LumaCheckoutProcessTestRunner" name="runScenario" time="86.893">
    <failure message="expected [Thank you for your purchase!] but found [Checkout]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Thank you for your purchase!] but found [Checkout]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at com.LUMA.stepDefinitions.CheckOutProcessStepDefinition.user_verify_order_confirmation_message_is_displayed(CheckOutProcessStepDefinition.java:76)
at âœ½.User Verify order confirmation message is displayed(file:///C:/Users/ASUS/eclipse-workspace/LUMA/src/test/resources/com.Luma.Feature/3s_CheckOutProcess.feature:20)
]]>
    </failure>
  </testcase> <!-- runScenario -->
</testsuite> <!-- com.LUMA.testRunner.LumaCheckoutProcessTestRunner -->
